version: '3.7'

volumes:
  gameshelf_postgres: {}
  gameshelf_postgres_backups: {}

services:
  db:
    image: 'postgres:latest'
    volumes:
      - gameshelf_postgres:/var/lib/postgresql/data
      - gameshelf_postgres_backups:/backups
    environment:
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails:
    build: ./ 
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container


